# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=70)),
                ('C_Code', models.CharField(max_length=30)),
                ('C_Classroom', models.CharField(max_length=30)),
                ('C_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=70)),
                ('Student_LastName', models.CharField(max_length=70)),
                ('Student_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=70)),
                ('Teacher_LastName', models.CharField(max_length=70)),
                ('Teacher_Email', models.EmailField(max_length=254)),
                ('Teacher_Phone', models.IntegerField()),
                ('Teacher_Office', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='C_Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment3.Teacher'),
        ),
    ]
