# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='C_Time',
            field=models.TimeField(),
        ),
    ]
