# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment3', '0003_courses_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_student',
            new_name='C_student',
        ),
    ]
